block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

timeout_sec = 3600

status = [
    "codecov/patch",
    "codecov/project",
    "continuous-integration/travis-ci/push",
]

[committer]
name = "BCBI Bot"
email = "bcbi-git@brown.edu"
